module.exports = [
  {
    id: 't19',
    name: 'T19/T19P/T19P E2',
    type: 'phone',
    template: 'yealink/default.cfg',
    accounts: 1,
  },
  {
    id: 't21',
    name: 'T21/T21 E2/T21P/T21P E2',
    type: 'phone',
    template: 'yealink/default.cfg',
    accounts: 2,
  },
  {
    id: 't23',
    name: 'T23/T23G',
    type: 'phone',
    template: 'yealink/default.cfg',
    accounts: 3,
  },
  {
    id: 't27',
    name: 'T27G/T27P',
    type: 'phone',
    template: 'yealink/default.cfg',
    accounts: 6,
  },
  {
    id: 't28',
    name: 'T28P',
    type: 'phone',
    template: 'yealink/default.cfg',
    accounts: 6,
  },
  {
    id: 't29',
    name: 'T29G',
    type: 'phone',
    template: 'yealink/default.cfg',
    accounts: 16,
  },
  {
    id: 't30',
    name: 'T30/T30P',
    type: 'phone',
    template: 'yealink/default.cfg',
    accounts: 1,
  },
  {
    id: 't31',
    name: 'T31/T31G',
    type: 'phone',
    template: 'yealink/default.cfg',
    accounts: 2,
  },
  {
    id: 't33',
    name: 'T33G',
    type: 'phone',
    template: 'yealink/default.cfg',
    accounts: 4,
  },
  {
    id: 't46',
    name: 'T46S/T46U',
    type: 'phone',
    template: 'yealink/default.cfg',
    accounts: 16,
  },
  {
    id: 'w52',
    name: 'W52P',
    type: 'phone',
    template: 'yealink/default.cfg',
    accounts: 5,
  },
  {
    id: 'w53',
    name: 'W53P',
    type: 'phone',
    template: 'yealink/default.cfg',
    accounts: 8,
  },
  {
    id: 'w60',
    name: 'W60P',
    type: 'phone',
    template: 'yealink/default.cfg',
    accounts: 8,
  },
];
